FROM python:3.8-slim-buster

RUN apt-get update -y
RUN apt-get install -y isc-dhcp-client net-tools dnsutils vim

WORKDIR /client
COPY . .

RUN pip3 install sockets

ENTRYPOINT ["tail", "-f", "/dev/null"]